name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: Leseratte10/d2xl-cios@master
      id: asdf
    - uses: actions/upload-artifact@v1
      with: 
        name: d2xl-cios
        path: build/

